// Generated by josh-approved-factory/scripts/generate-credits.mjs.
// Source: credits-config.json + package.json + node_modules.
// Do not edit by hand — re-run the generator after dep updates.

export interface CreditEntry {
  name: string;
  version: string;
  license: string;
  url: string;
}

export const CREDITS_INTRO = "Grocery List is built on the work of these open-source projects.";

export const CREDITS: CreditEntry[] = [
  {
    "name": "React Native",
    "version": "0.81.5",
    "license": "MIT",
    "url": "https://reactnative.dev/"
  },
  {
    "name": "Expo",
    "version": "54.0.34",
    "license": "MIT",
    "url": "https://github.com/expo/expo/tree/main/packages/expo"
  },
  {
    "name": "React Navigation",
    "version": "7.2.4",
    "license": "MIT",
    "url": "https://reactnavigation.org"
  },
  {
    "name": "Zustand",
    "version": "5.0.13",
    "license": "MIT",
    "url": "https://github.com/pmndrs/zustand"
  },
  {
    "name": "Expo SQLite",
    "version": "16.0.10",
    "license": "MIT",
    "url": "https://docs.expo.dev/versions/latest/sdk/sqlite/"
  },
  {
    "name": "Reanimated",
    "version": "4.1.7",
    "license": "MIT",
    "url": "https://docs.swmansion.com/react-native-reanimated"
  },
  {
    "name": "react-native-svg",
    "version": "15.12.1",
    "license": "MIT",
    "url": "https://github.com/react-native-community/react-native-svg"
  },
  {
    "name": "react-native-qrcode-svg",
    "version": "6.3.21",
    "license": "MIT",
    "url": "https://github.com/Expensify/react-native-qrcode-svg#readme"
  },
  {
    "name": "Expo Camera",
    "version": "17.0.10",
    "license": "MIT",
    "url": "https://docs.expo.dev/versions/latest/sdk/camera/"
  },
  {
    "name": "Noble Curves",
    "version": "2.2.0",
    "license": "MIT",
    "url": "https://paulmillr.com/noble/"
  },
  {
    "name": "Noble Hashes",
    "version": "2.2.0",
    "license": "MIT",
    "url": "https://paulmillr.com/noble/"
  },
  {
    "name": "TweetNaCl.js",
    "version": "1.0.3",
    "license": "Unlicense",
    "url": "https://tweetnacl.js.org"
  },
  {
    "name": "Lucide",
    "version": "1.16.0",
    "license": "ISC",
    "url": "https://lucide.dev"
  },
  {
    "name": "IBM Plex",
    "version": "",
    "license": "OFL 1.1",
    "url": "https://www.ibm.com/plex/"
  }
];
